import type { Metadata } from "next";
import { Passion_One } from "next/font/google";
import "./globals.css";

const passionSans = Passion_One({
  variable: "--font-passion",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${passionSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
